#!/bin/bash
set -e

if [ ! -e $PREFIX/compiled-deps ]; then
	echo "Dependencies have not been compiled"
	exit
fi

if [ -e $PREFIX/compiled-dl-fldigi ]; then
	echo "DL-Fldigi has already been compiled"
	exit
fi

cd $SRC/dl-fldigi
autoreconf -vfi
./configure $CONFLAGS --disable-nls --with-ptw32=$PREFIX/ptw32 PKG_CONFIG=$PREFIX/bin/$HTGT-pkg-config FLTK_CONFIG=$PREFIX/bin/fltk-config XMLRPC_C_CONFIG=$PREFIX/bin/xmlrpc-c-config CURL_CFLAGS="`$PREFIX/bin/$HTGT-pkg-config libcurl --static --cflags`" CURL_LIBS="`$PREFIX/bin/$HTGT-pkg-config libcurl --static --libs` -L$PREFIX/zlib/lib"
make -j$MAKE_CORES
make hamlib-static
make nsisinst
cp -v $PREFIX/src/dl-fldigi/src/*.exe $PREFIX/bin

touch $PREFIX/compiled-dl-fldigi
