#!/bin/bash
set -e

TINSTALL=""

if [ ! -x /usr/bin/i586-mingw32msvc-gcc ]; then
	TINSTALL="$TINSTALL mingw32"
fi

if [ ! -x /usr/bin/makensis ]; then
	TINSTALL="$TINSTALL nsis"
fi

if [ "x$TINSTALL" != "x" ]; then
	sudo -v
	sudo aptitude install $TINSTALL
	sudo -k
fi

if [ "x$PREFIX" == "x" ]; then
	echo "No \$PREFIX set"
	exit
fi

cd $PREFIX
source ./env
source ./download_locations

if [ -a $PREFIX/downloaded ]; then
	echo "Already downloaded"
	exit
fi

cat > $PREFIX/bin/$HTGT-pkg-config <<EOF
#!/bin/sh

export PKG_CONFIG_LIBDIR=\$PREFIX/lib/pkgconfig
export PKG_CONFIG_PATH=\$PKG_CONFIG_PATH_MINGW32MSVC

exec pkg-config "\$@"
EOF

chmod +x $PREFIX/bin/$HTGT-pkg-config

cd $SRC

mkdir dl-fldigi		&& wget -O - -q "$DL_FLDIGI"	| tar -xvzC dl-fldigi	--strip-components=1
mkdir ptw32		&& wget	-O - -q "$PTW32"	| tar -xvzC ptw32	--strip-components=1
mkdir zlib		&& wget -O - -q "$ZLIB"		| tar -xvzC zlib	--strip-components=1
mkdir libpng		&& wget -O - -q "$LIBPNG"	| tar -xvzC libpng	--strip-components=1
mkdir fltk		&& wget -O - -q "$FLTK"		| tar -xvzC fltk	--strip-components=1
mkdir samplerate	&& wget -O - -q "$SAMPLERATE"	| tar -xvzC samplerate	--strip-components=1
mkdir sndfile		&& wget -O - -q "$SNDFILE"	| tar -xvzC sndfile	--strip-components=1
mkdir hamlib		&& wget -O - -q "$HAMLIB"	| tar -xvzC hamlib	--strip-components=1
mkdir binutils		&& wget -O - -q "$BINUTILS"	| tar -xvzC binutils	--strip-components=1
mkdir curl		&& wget -O - -q "$CURL"		| tar -xvzC curl	--strip-components=1

svn export $XMLRPCC xmlrpc
svn export $PORTAUDIO portaudio

cd $SRC/fltk		&& wget -O - -q $FLTK_PATCH		| patch -p1
cd $SRC/xmlrpc		&& wget -O - -q $XMLRPC_PATCH		| patch -p1

cd $SRC/hamlib
sed -i "s/#include <unistd\.h>/\/* #include <unistd.h> *\//" src/{serial.c,event.c,iofunc.c}

touch $PREFIX/downloaded
