#!/bin/bash
set -e

if [ ! $# -eq 0 ]; then
	echo "Usage: $0"
	exit
fi

if [ "x$PREFIX" == "x" ]; then
	echo "No \$PREFIX set"
	exit
fi

cd $PREFIX
source ./env

cd $SRC/dl-fldigi
git clean -fxd
git pull origin master

rm -f $PREFIX/compiled-dl-fldigi

if [ ! -e $PREFIX/compiled-deps ]; then
	cd $PREFIX
	source ./compile-deps
fi

cd $PREFIX
source ./compile-dl-fldigi
