#!/bin/bash
set -e

IFS_O=$IFS
IFS=$(echo -en '\0')

cd $1
LOCAL_PREFIX=`pwd`

PREFIX=/tmp/`basename $LOCAL_PREFIX`
ln -s $LOCAL_PREFIX $PREFIX

echo "Location is $LOCAL_PREFIX"
echo "Safe name is $PREFIX"

export PREFIX
IFS=$IFS_O
