#!/bin/bash
set -e

MY_SCRIPTS=`pwd`

PREFIX=`mktemp -d /tmp/dl-fldigi.XXXXXX`
ln -s $PREFIX `basename $PREFIX`
cp compile download download_locations env $PREFIX

cd $PREFIX
PREFIX=`pwd`
mkdir $PREFIX/{bin,src,lib,lib/pkgconfig}

echo Temporary build location is $PREFIX

export PREFIX
